### ISSUE TITLE
Bug: class fields not supported and broke parser

### ISSUE THREAD

**Issue by Akiyamka** [i18next/i18next-parser#148]
- Is this a bug or a feature request?
This is a bug
- What version are you running (`0.x` or `1.x`)? 
`1.0.0-beta34`
- Which runner (cli, gulp...)?
cli

## What I'm trying to do?
Try look at list of used keys in React components (where used react-i18next)

## How am I doing it?
I install next packages:
`i18next-parser`, `acorn-jsx`, `acorn-stage3`

Here is my config file:
```js
const acornStage3 = require('acorn-stage3/inject');
module.exports = {
  contextSeparator: '_',
  createOldCatalogs: true,
  defaultNamespace: 'translation',
  defaultValue: '',
  indentation: 2,
  keepRemoved: false,
  keySeparator: '.',
  lexers: {
    htm: ['HTMLLexer'],
    html: ['HTMLLexer'],
    js: [{
      lexer: 'JsxLexer',
      injectors: [acornStage3],
      plugins: {
        stage3: true,
      },
    }],
    default: ['JavascriptLexer']
  },
  lineEnding: 'auto',
  locales: ['en', 'fr'],
  namespaceSeparator: ':',
  output: 'locales/$LOCALE/$NAMESPACE.json',
  input: undefined,
  reactNamespace: true,
  sort: false,
  useKeysAsDefaultValue: false,
  verbose: true
}
```

The command I'm running:
```
i18next ./src/components/**/*.js -oc -c ./i18next-parser.config.js
```

## What was the result?
Parser crush when start parsing components with [class fields](https://github.com/tc39/proposal-class-fields).
Log:
```
➜ npm run i18next

> event-brief@0.0.1 i18next /home/cherrytea/Git/eventbrief/front-end
> i18next ./src/components/**/*.js -oc -c ./i18next-parser.config.js

  i18next Parser
  --------------
  Input:
  ./src/components/AnchorMenu/index.js,
  ./src/components/Forecast/index.js,
  ...
  ./src/components/Login/index.js

  Output: -c

  [read]  /src/components/AnchorMenu/index.js
Parsing /src/components/AnchorMenu/index.js
  [read]  /src/components/Forecast/index.js
Parsing /src/components/Forecast/index.js
...
  [read] /src/components/Login/index.js
Parsing /src/components/Login/index.js

.../node_modules/i18next-parser/dist/parser.js:70

}} catch (err) {_didIteratorError = true;_iteratorError = err;} finally {try {if (!_iteratorNormalCompletion && _iterator.return) {_iterator.return();}} finally {if (_didIteratorError) {throw _iteratorError;}}}
                                                                                                                                                                                                  ^

SyntaxError: Unexpected token (19:13)
    at Parser.pp$4.raise (.../node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (.../node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp.expect (.../node_modules/acorn/dist/acorn.js:641:26)
    at Parser.pp$3.parseMethod (.../node_modules/acorn/dist/acorn.js:2530:8)
    at Parser.pp$1.parseClassMethod (.../node_modules/acorn/dist/acorn.js:1316:23)
    at Parser.pp$1.parseClassMember (.../node_modules/acorn/dist/acorn.js:1305:8)
    at Parser.pp$1.parseClass (.../node_modules/acorn/dist/acorn.js:1250:25)
    at Parser.pp$1.parseStatement (.../node_modules/acorn/dist/acorn.js:779:17)
    at Parser.pp$1.parseTopLevel (.../node_modules/acorn/dist/acorn.js:706:23)
    at Parser.parse (.../node_modules/acorn/dist/acorn.js:551:15)
```
 
19:13 from Login/index.js
```js
class Login extends Component {
  getFormRef = node => { this._formRef = node };   // 19 string is here
```
## What was I expecting?

I expect that stage 3 proposal dont't broke praser with `stage3: true` setting

**Comment by Akiyamka** [comment]
look like [acorn-stage3](https://github.com/acornjs/acorn-stage3) support class fields so I can't understand, why it doesn't work ?

**Comment by karellm** [comment]
It looks like your config file is at fault. You want the key to be `lexers.js.acorn.injectors` where you have `lexers.js.injectors`. See [here](https://github.com/i18next/i18next-parser#javascript)

**Comment by Akiyamka** [comment]
@karellm thank you, you're right. I corrected the config and now it looks like this:
```js
const acornStage3 = require('acorn-stage3');
module.exports = {
  contextSeparator: '_',
  createOldCatalogs: true,
  defaultNamespace: 'translation',
  defaultValue: '',
  indentation: 2,
  keepRemoved: false,
  keySeparator: '.',
  lexers: {
    htm: ['HTMLLexer'],
    html: ['HTMLLexer'],
    js: [{
      lexer: 'JsxLexer',
      acorn: {
        injectors: [acornStage3],
        plugins: {
          stage3: true,
        },
      }
    }],
    default: ['JavascriptLexer']
  },
  lineEnding: 'auto',
  locales: ['en', 'fr'],
  namespaceSeparator: ':',
  output: 'locales/$LOCALE/$NAMESPACE.json',
  input: undefined,
  reactNamespace: true,
  sort: false,
  useKeysAsDefaultValue: false,
  verbose: true
}
```
But after this changes i got error 

```
Error: Lexer 'undefined' does not exist
at .../node_modules/i18next-parser/dist/parser.js:70:32
```

I put some console.log-s in parser.js and see strange behavior:
```
Constructor -> this.lexers.js [ { lexer: 'JsxLexer', acorn: { injectors: [Array], plugins: [Object] } } ]


  [read]  .../src/components/AnchorMenu/index.js
  [log] _createClass -> this.lexers.js:
  [ { lexer: 'JsxLexer', acorn: { injectors: [Array], plugins: [Object] } } ]


  [read]  .../src/components/App/index.js
  [log] _createClass -> this.lexers.js:
  [ { acorn: { injectors: [Array], plugins: [Object] }, attr: 'i18nKey' } ]

message Error: Lexer 'undefined' does not exist
```
For some reason lexer name `lexer: 'JsxLexer'` disappears on second file. 
I experimented a bit, it seems it does not matter which file will be the second.

**Comment by Akiyamka** [comment]
I created minimal reproduction example in this repo:
https://github.com/Akiyamka/i18next-parser-reproduce

**Comment by karellm** [comment]
It drove me nuts for a while but your command is wrong. You defined the `-c` option twice. 

`"i18next": "i18next ./src/components/**/*.js -oc ./i18next-parser.config.js"`

**Comment by Akiyamka** [comment]
@karellm great thanks!
