### ISSUE TITLE
i18next-parser for gulp is not work

### ISSUE THREAD

**Issue by huanglijiao** [i18next/i18next-parser#154]
gulpfile.js:
const i18nextParser = require('i18next-parser');
const gulp = require('gulp');

gulp.task('i18next', function() {
  gulp.src(['./pages/**/*', './components/**/*'])
    .pipe(new i18nextParser({
      locales: ['en'],
      namespace: 'common',
      output: 'static/locales/$LOCALE/$NAMESPACE.json'
    }))
    .pipe(gulp.dest('./'));
});

gulp.task('t', ['i18next']);

err:
[21:37:20] Using gulpfile /Applications/hust-dev/joox-web-nextjs/gulpfile.js
[21:37:20] Starting 'i18next'...
[21:37:20] 'i18next' errored after 6.27 ms
[21:37:20] TypeError: i18nextParser is not a constructor
    at Gulp.<anonymous> (/Applications/hust-dev/joox-web-nextjs/gulpfile.js:6:11)
    at module.exports (/Applications/hust-dev/joox-web-nextjs/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Applications/hust-dev/joox-web-nextjs/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Applications/hust-dev/joox-web-nextjs/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Applications/hust-dev/joox-web-nextjs/node_modules/orchestrator/index.js:134:8)
    at /Users/hust/.npm-global/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

the gulpfile.js:
const i18nextParser = require('i18next-parser').gulp;
const gulp = require('gulp');

gulp.task('i18next', function() {
  gulp.src(['./pages/**/*', './components/**/*'])
    .pipe(new i18nextParser({
      locales: ['en'],
      namespace: 'common',
      output: 'static/locales/$LOCALE/$NAMESPACE.json'
    }))
    .pipe(gulp.dest('./'));
});

gulp.task('t', ['i18next']);

err:
[21:37:55] Using gulpfile /Applications/hust-dev/joox-web-nextjs/gulpfile.js
[21:37:55] Starting 'i18next'...
[21:37:55] Finished 'i18next' after 6.8 ms
[21:37:55] Starting 't'...
[21:37:55] Finished 't' after 22 μs
/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/dist/parser.js:70
        }} catch (err) {_didIteratorError = true;_iteratorError = err;} finally {try {if (!_iteratorNormalCompletion && _iterator.return) {_iterator.return();}} finally {if (_didIteratorError) {throw _iteratorError;}}}
                                                                                                                                                                                                  ^

SyntaxError: Unexpected token (8:17)
    at Parser.pp$4.raise (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp$3.parseExprAtom (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:2196:10)
    at Parser.pp$3.parseExprSubscripts (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:2024:17)
    at Parser.pp$3.parseExprOps (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:1925:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:2238:30)
    at Parser.pp$3.parseExprAtom (/Applications/hust-dev/joox-web-nextjs/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:2163:41)

**Comment by karellm** [comment]
Please format your request with the given template and reopen an issue.
