### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by benmonro** [i18next/i18next-parser#165]
- Is this a bug or a feature request?
both?
- What version are you running (`0.x` or `1.x`)? 
@1.0.0-beta34
- Which runner (cli, gulp...)?
CLI
## What I'm trying to do?
extract translations from a file

## How am I doing it?

```module.exports = {
    lexers: {
        js: ['JsxLexer'],
        jsx: ['JsxLexer'],
        default: ['JsxLexer']
    },
    output: 'locales/$LOCALE/$NAMESPACE.yml',
    keySeparator: false,
    namespaceSeparator: false,
    useKeysAsDefaultValue: true
}```

Here is my config file:

```
module.exports = {
    lexers: {
        js: ['JsxLexer'],
        jsx: ['JsxLexer'],
        default: ['JsxLexer']
    },
    output: 'locales/$LOCALE/$NAMESPACE.yml',
    keySeparator: false,
    namespaceSeparator: false,
    useKeysAsDefaultValue: true
}
```

The command I'm running:

```
i18next src/path/to/file.js -c i18next.config.js
```

## What was the result?

```[read]  /Users/b0m01v7/Code/grocery-electrode/src/client/components/cart/Cart.js
/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/dist/parser.js:70
        }} catch (err) {_didIteratorError = true;_iteratorError = err;} finally {try {if (!_iteratorNormalCompletion && _iterator.return) {_iterator.return();}} finally {if (_didIteratorError) {throw _iteratorError;}}}
                                                                                                                                                                                                  ^

SyntaxError: Unexpected token (78:22)
    at Parser.pp$4.raise (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:2757:13)
    at Parser.pp.unexpected (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:647:8)
    at Parser.pp.expect (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:641:26)
    at Parser.pp$3.parseMethod (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:2530:8)
    at Parser.pp$1.parseClassMethod (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:1316:23)
    at Parser.pp$1.parseClassMember (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:1305:8)
    at Parser.pp$1.parseClass (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:1250:25)
    at Parser.pp$1.parseStatement (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:779:17)
    at Parser.pp$1.parseTopLevel (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:706:23)
    at Parser.parse (/Users/b0m01v7/Code/grocery-electrode/node_modules/i18next-parser/node_modules/acorn/dist/acorn.js:551:15)
error Command failed with exit code 1.```

## What was I expecting?

It would be nice if the unexpected token error would show where in the code it's getting an error.  as it is now, i have to try to find it myself.

**Comment by benmonro** [comment]
after some investigation it appears to be having issues with static props:

```javascript
class Cart extends Component {
  static defaultProps = {
    userSlotValidationCheckPassed: false,
    showModal: () => { },
    closeModal: () => { },
    onClickAddCard: () => { }
  };
// ...
}
```

**Comment by bitttttten** [comment]
I think it's because acorn doesn't support stage 3 proposals. Check out my comment here to see if it helps: https://github.com/i18next/i18next-parser/issues/155#issuecomment-512177013 and the discussion in this thread.

Although following my comment above may lead you into other problems with webpack if you are using it as it'll mess up the dependencies and webpack will break with the version of acorn I suggest.

**Comment by karellm** [comment]
I'm closing this in favor of #155. This issue seems related to acorn which is really a big mess atm.
