### ISSUE TITLE
TypeError with 1.0.0-beta36

### ISSUE THREAD

**Issue by edizcelik** [i18next/i18next-parser#188]
- Is this a bug or a feature request?
Bug
- What version are you running (`0.x` or `1.x`)? 
1.0.0-beta36
- Which runner (cli, gulp...)?
CLI

## What I'm trying to do?

I am trying to parse my `ts` and `tsx` files.

## How am I doing it?

Here is my config file:

```
module.exports = {
  contextSeparator: "_",
  createOldCatalogs: true,
  defaultNamespace: "common",
  defaultValue: "_NOTRANSLATION_",
  indentation: 2,
  keepRemoved: false,
  keySeparator: ".",
  lexers: {
    js: ['JavascriptLexer'],
    ts: ["JavascriptLexer"],
    jsx: ['JsxLexer'],
    tsx: ['JsxLexer'],

    default: ["JavascriptLexer"]
  },
  lineEnding: "auto",
  locales: ["en", "fr"],
  namespaceSeparator: ":",
  output: "./src/locales/$LOCALE/$NAMESPACE.json",
  input: ["./src/**/*.tsx", "./src/**/*.ts"],
  reactNamespace: false,
  sort: false,
  useKeysAsDefaultValue: false,
  verbose: false
};
```

The command I'm running:

```
i18next --config ./i18next-parser.config.js
```

## What was the result?

I'm getting a TypeError. Here is the details:

```
        }} catch (err) {_didIteratorError = true;_iteratorError = err;} finally {try {if (!_iteratorNormalCompletion && _iterator.return) {_iterator.return();}} finally {if (_didIteratorError) {throw _iteratorError;}}}
                                                                                                                                                                                                  ^

TypeError: Cannot read property 'text' of undefined
    at JavascriptLexer.expressionExtractor (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/i18next-parser/dist/lexers/javascript-lexer.js:73:50)
    at parseTree (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/i18next-parser/dist/lexers/javascript-lexer.js:19:46)
    at visitNode (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/typescript/lib/typescript.js:17739:24)
    at Object.forEachChild (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/typescript/lib/typescript.js:18019:24)
    at NodeObject.forEachChild (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/typescript/lib/typescript.js:130164:23)
    at parseTree (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/i18next-parser/dist/lexers/javascript-lexer.js:26:14)
    at visitNodes (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/typescript/lib/typescript.js:17748:30)
    at Object.forEachChild (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/typescript/lib/typescript.js:17979:24)
    at NodeObject.forEachChild (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/typescript/lib/typescript.js:130164:23)
    at parseTree (/Users/edizcelik/Documents/Hipo/pascal-web-app/node_modules/i18next-parser/dist/lexers/javascript-lexer.js:26:14)
```

## What was I expecting?

I expected the script to run successfully and generate translation files. Note that when I use `1.0.0-beta34` with `acorn@4.1.1`, I don't encounter this however I have dynamic imports in my project and I bumped up the version to `1.0.0-beta36` as this version no longer relies on acorn.

**Comment by vincaslt** [comment]
Thanks for the report, it would've helped to get a code example which fails with this error. #191 will fix this error.
