### ISSUE TITLE
Cannot read property 'text' of undefined in javascript-lexer

### ISSUE THREAD

**Issue by latuszek** [i18next/i18next-parser#199]
- Is this a bug or a feature request?
Bug
- What version are you running (`0.x` or `1.x`)? 
1.0.0
- Which runner (cli, gulp...)?
gulp

## What I'm trying to do?

I trying to run following gulp task:
```js
const gulp = require('gulp');
const i18nextParser = require('i18next-parser').gulp;

gulp.task('i18n', () => {
    gulp.src('src/**/*.{js,jsx}')
        .pipe(new i18nextParser({
            locales: ['pl'],
            namespace: 'cmp',
            functions: ['t'],
            attributes: ['i18nKey'],
            output: 'static/locales/$LOCALE/$NAMESPACE.json',
            sort: true,
            verbose: true
        }))
        .pipe(gulp.dest('src/static/locales'))
});
```

## How am I doing it?

Via `yarn gulp i18n`

## What was the result?

```
(...)
Parsing C:\workspace\code\cargo\src\main\react\src\components\BookingTimeSlot\Slot.jsx
[14:46:26] 'i18n' errored after 752 ms
[14:46:26] TypeError: Cannot read property 'text' of undefined
    at JsxLexer.expressionExtractor (C:\workspace\code\cargo\src\main\react\node_modules\i18next-parser\dist\lexers\javascript-lexer.js:73:28)
    at parseTree (C:\workspace\code\cargo\src\main\react\node_modules\i18next-parser\dist\lexers\jsx-lexer.js:20:48)
    at visitNode (C:\workspace\code\cargo\src\main\react\node_modules\typescript\lib\typescript.js:17765:24)
    at Object.forEachChild (C:\workspace\code\cargo\src\main\react\node_modules\typescript\lib\typescript.js:18179:21)
    at NodeObject.forEachChild (C:\workspace\code\cargo\src\main\react\node_modules\typescript\lib\typescript.js:130234:23)
    at parseTree (C:\workspace\code\cargo\src\main\react\node_modules\i18next-parser\dist\lexers\jsx-lexer.js:34:14)
    at visitNodes (C:\workspace\code\cargo\src\main\react\node_modules\typescript\lib\typescript.js:17774:30)
    at Object.forEachChild (C:\workspace\code\cargo\src\main\react\node_modules\typescript\lib\typescript.js:18159:21)
    at NodeObject.forEachChild (C:\workspace\code\cargo\src\main\react\node_modules\typescript\lib\typescript.js:130234:23)
    at parseTree (C:\workspace\code\cargo\src\main\react\node_modules\i18next-parser\dist\lexers\jsx-lexer.js:34:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## What was I expecting?

Not throwing an error?

**Comment by latuszek** [comment]
It may help, that the only place in which I am using translation in the `Stlot.jsx` is this:
```jsx
{t('Booking.TimeSlotBookingView.Slot.booked', { ...slot })}
```
So it may be the spread operator.

**Comment by vincaslt** [comment]
It could be. Would you be able to post more of the code, like how `slot` is constructed? It seems to me that cases like this could be simplified, and writing it this way may be unnecessary.

**Comment by latuszek** [comment]
`slot` has following shape:
```js
PropTypes.shape({
    timeSlotStart: PropTypes.instanceOf(moment),
    timeSlotEnd: PropTypes.instanceOf(moment),
    capacity: PropTypes.number,
    bookedCount: PropTypes.number
});
```

**Comment by karellm** [comment]
@vincaslt Do you think you could have a look?

**Comment by alk-mandrianarijaona** [comment]
I also have the same issue on code where there is a spread operator. Have you found a solution for this?

**Comment by latuszek** [comment]
Only a workaround of not using a spread operator.

**Comment by Antonhansel** [comment]
I'm having the same issue, with a spread operator as well.
I'm curious as of why this happens, any idea what causes this issue ?

**Comment by karellm** [comment]
I found some time to investigate and fix this. Starting with `4.1.0` the spread operator is supported but emits a warning.
