### ISSUE TITLE
read error with CLI

### ISSUE THREAD

**Issue by 1bw** [i18next/i18next-parser#22]
Can't seem to get this to work.  I'm on win7 using version 0.3.4. Throws an error trying to read in the locales dir.  It will create the dir and leave it empty.

```
C:\l2>i18next "C:\l2"

i18next Parser
--------------
Input:  C:\l2
Output: C:\l2\locales


[parse] C:\l2\i18next-1.7.4.js
[parse] C:\l2\index.html

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'C:\l2\locales\en\,
        reuseSuffix.json'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.writeFileSync (fs.js:971:15)
    at Transform._transform (C:\Users\user\AppData\Roaming\npm\node_modules\
i18next-parser\bin\cli.js:127:12)
    at Transform._read (C:\Users\user\AppData\Roaming\npm\node_modules\i18ne
xt-parser\node_modules\through2\node_modules\readable-stream\lib\_stream_transfo
rm.js:184:10)
    at Transform._write (C:\Users\user\AppData\Roaming\npm\node_modules\i18n
ext-parser\node_modules\through2\node_modules\readable-stream\lib\_stream_transf
orm.js:172:12)
    at doWrite (C:\Users\user\AppData\Roaming\npm\node_modules\i18next-parse
r\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237
:10)
    at writeOrBuffer (C:\Users\user\AppData\Roaming\npm\node_modules\i18next
-parser\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.
js:227:5)
    at Transform.Writable.write (C:\Users\user\AppData\Roaming\npm\node_modu
les\i18next-parser\node_modules\through2\node_modules\readable-stream\lib\_strea
m_writable.js:194:11)
    at write (_stream_readable.js:585:24)
    at flow (_stream_readable.js:594:7)

C:\l2>
```

**Comment by karellm** [comment]
Has I didn't hear back from you I will consider this error solve. Please open a new ticket if it is not.
