### ISSUE TITLE
Crash when directory name matches file pattern with no explanation

### ISSUE THREAD

**Issue by kaaboaye** [i18next/i18next-parser#252]
## 🐛 Bug Report

If any of directories in project matches file pattern it crashes without any explanation. Only after running with the debugger I was able to determine which directory was causing problem.

```
internal/fs/utils.js:299
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:590:3)
    at tryReadSync (fs.js:364:20)
    at Object.readFileSync (fs.js:401:19)
    at i18nTransform._transform (/home/mieszkowaw/Code/surferlocal/app/node_modules/i18next-parser/dist/transform.js:86:32)
    at i18nTransform.Transform._read (_stream_transform.js:205:10)
    at i18nTransform.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at i18nTransform.Writable.write (_stream_writable.js:303:10)
    at DestroyableTransform.ondata (/home/mieszkowaw/Code/surferlocal/app/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:314:20) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```

## To Reproduce

1. Create project with dir `Foo.ts`
2. Run `i18next 'src/**/*.{ts,tsx}'`

## Expected behavior

Crash with meaningful message pointing to that directory or ignore directories in the first place.

## Your Environment

"i18next-parser": "^3.3.0"

**Comment by karellm** [comment]
Thanks, it should be fixed in `3.5.0`
