### ISSUE TITLE
Parse full meteor app folder

### ISSUE THREAD

**Issue by shkomg** [i18next/i18next-parser#27]
Hi,

while trying to parse all meteor app folder got such a mistake:
[parse] /home/username/.meteor/packages/webapp/.1.1.6.6iir9q++os+web.browser+web.cordova/npm/node_modules/connect/node_modules/multiparty/node_modules/readable-stream/test/simple/test-stream2-writable.js
fs.js:113
      throw er;
      ^
Error: Path must be a string without null bytes.
    at nullCheck (fs.js:111:14)
    at Object.fs.openSync (fs.js:501:3)
    at Object.fs.writeFileSync (fs.js:1103:15)
    at Transform._transform (/usr/lib/node_modules/i18next-parser/bin/cli.js:125:12)
    at Transform._read (/usr/lib/node_modules/i18next-parser/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/lib/node_modules/i18next-parser/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/lib/node_modules/i18next-parser/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:238:10)
    at writeOrBuffer (/usr/lib/node_modules/i18next-parser/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:228:5)
    at Transform.Writable.write (/usr/lib/node_modules/i18next-parser/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:195:11)
    at Parser.ondata (_stream_readable.js:540:20)

```


```

**Comment by shkomg** [comment]
well, with filters ```i18next ~/HostApp/ -r -l en,ua -f t,tt --fileFilter '*.html,*.js' --directoryFilter '!.git, !.meteor'``` it works just great! 

Thank you
