### ISSUE TITLE
Error from JSX spread attributes such as `<a {...props}>`

### ISSUE THREAD

**Issue by joshkel** [i18next/i18next-parser#908]
## 🐛 Bug Report

Running i18next-parser on a JSX tag that spreads attributes results in the following error.

```
TypeError: Cannot read properties of undefined (reading 'escapedText')
    at file:///Users/josh/src/node_modules/i18next-parser/dist/lexers/jsx-lexer.js:228:51
    at Array.find (<anonymous>)
    at file:///Users/josh/src/node_modules/i18next-parser/dist/lexers/jsx-lexer.js:227:66
    at Array.map (<anonymous>)
    at JsxLexer.parseChildren (file:///Users/josh/src/node_modules/i18next-parser/dist/lexers/jsx-lexer.js:214:7)
    at JsxLexer.nodeToString (file:///Users/josh/src/node_modules/i18next-parser/dist/lexers/jsx-lexer.js:178:41)
    at JsxLexer.jsxExtractor (file:///Users/josh/src/node_modules/i18next-parser/dist/lexers/jsx-lexer.js:144:46)
    at parseTree (file:///Users/josh/src/node_modules/i18next-parser/dist/lexers/jsx-lexer.js:41:41)
    at visitNodes (/Users/josh/src/node_modules/typescript/lib/typescript.js:27937:24)
    at forEachChildInJsxElement (/Users/josh/src/node_modules/typescript/lib/typescript.js:28705:61)```

## To Reproduce

```js
<Trans>Please <a {...hrefProps}>click here.</a></Trans>
```

## Expected behavior

i18next-parser cleanly extracts the translation string.

## Your Environment

- *runtime version*: Node 18.16.1
- *i18next version*: i18next-parser 8.7.0
- *os*: Mac
- *any other relevant information*: This may have been introduced in #862.

**Comment by karellm** [comment]
Fix as of `8.8.0`
