### ISSUE TITLE
Errors with setting js lexer

### ISSUE THREAD

**Issue by alexshurik** [i18next/i18next-parser#91]
- Bug
- 1.0.0-beta12
- cli

## What I'm trying to do?

*Configure js lexer*

## How am I doing it?

Here is my config file:

```
module.exports = {
    reactNamespace: true,
    locales: ['ru', 'en'],
    output: 'src/scripts/i18n',
    createOldCatalogs: false,
    defaultNamespace: 'html',
    lexers: {
        js: [
            {
                lexer: 'JavascriptLexer',
                functions: ['t']
            }
        ],
    }
};
```

The command I'm running:

```
i18next 'src/scripts/**/*.js' 'index.html' -c i18next-parser-config.js
```

## What was the result?

*Getting this error:*

```
/usr/local/lib/node_modules/i18next-parser/bin/cli.js:92
    console.log('  [error] '.red + message + ': ' + region.trim())
                                                           ^

TypeError: Cannot read property 'trim' of undefined
    at i18nTransform.<anonymous> (/usr/local/lib/node_modules/i18next-parser/bin/cli.js:92:60)
    at emitOne (events.js:120:20)
    at i18nTransform.emit (events.js:210:7)
    at Parser.<anonymous> (/usr/local/lib/node_modules/i18next-parser/dist/index.js:46:61)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at /usr/local/lib/node_modules/i18next-parser/dist/parser.js:60:18
    at Array.forEach (<anonymous>)
    at Parser.parse (/usr/local/lib/node_modules/i18next-parser/dist/parser.js:45:14)
    at i18nTransform._transform (/usr/local/lib/node_modules/i18next-parser/dist/index.js:65:33)
```

## What was I expecting?

*Succesful translations parsing*

## Thoughts and results of my experiments:

1. Commented this line (/usr/local/lib/node_modules/i18next-parser/bin/cli.js:92)
`console.log('  [error] '.red + message + ': ' + region.trim())`

2. Got another error
```
/usr/local/lib/node_modules/i18next-parser/dist/parser.js:63
        var Lexer = new lexersMap[lexerName](lexerOptions);
                    ^

TypeError: lexersMap[lexerName] is not a constructor
    at /usr/local/lib/node_modules/i18next-parser/dist/parser.js:63:21
    at Array.forEach (<anonymous>)
    at Parser.parse (/usr/local/lib/node_modules/i18next-parser/dist/parser.js:45:14)
    at i18nTransform._transform (/usr/local/lib/node_modules/i18next-parser/dist/index.js:65:33)
    at i18nTransform.Transform._read (_stream_transform.js:186:10)
    at i18nTransform.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at i18nTransform.Writable.write (_stream_writable.js:290:11)
    at DestroyableTransform.ondata (/usr/local/lib/node_modules/i18next-parser/node_modules/readable-stream/lib/_stream_readable.js:619:20)
```

That's because  `lexersMap[lexerName]` is undefined

3. Commented this line (/usr/local/lib/node_modules/i18next-parser/dist/parser.js:55)
`delete lexerConfig.lexer;`

4. After that, everything works as expected. Didn't understand, why do you delete `lexerConfig.lexer` and why does it work for other lexers (e.g. handlebars).
Unfortunately, do not have enough time to further investigation

**Comment by vityukBogdan** [comment]
Can try to use this version
"i18next-parser": "1.0.0-beta29",
